//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VicGenesis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using VicGenesis.Models;

    public partial class regionalDatabaseEntities : DbContext
    {
        public regionalDatabaseEntities()
            : base("name=regionalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Area>()
                .Property(e => e.C_Area_Name_)
                .IsUnicode(false);

            modelBuilder.Entity<Area>()
                .Property(e => e.Description)
                .IsUnicode(false);

            modelBuilder.Entity<Area>()
                .Property(e => e.Latitude)
                .HasPrecision(10, 8);

            modelBuilder.Entity<Area>()
                .Property(e => e.Longitude)
                .HasPrecision(11, 8);

            modelBuilder.Entity<Event>()
                .Property(e => e.Area_Name)
                .IsUnicode(false);
        }
    
        public virtual DbSet<Victoria> Victorias { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Event> Events { get; set; }
    }
}
