//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VicGenesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Victoria
    {
        public string COMM_CODE { get; set; }
        public string Community_Name { get; set; }
        public string Community_Type { get; set; }
        public string DHS_Region { get; set; }
        public string Map_Reference { get; set; }
        public Nullable<double> Area_km_sq { get; set; }
        public string Location { get; set; }
        public Nullable<double> Road_distance_to_GPO_km { get; set; }
        public string Local_Government_Area { get; set; }
        public Nullable<double> Population_density { get; set; }
        public string Primary_Care_Partnership { get; set; }
        public Nullable<double> Number_of_localities { get; set; }
        public string ABS_Remoteness_Area { get; set; }
        public string Population_Difference { get; set; }
        public Nullable<double> Funded_Activity_Types { get; set; }
        public Nullable<double> Funded_Services { get; set; }
        public Nullable<double> HACC_Services { get; set; }
        public Nullable<double> Child_Protection_Services { get; set; }
        public Nullable<double> Community_Health_Services { get; set; }
        public Nullable<double> Homelessness { get; set; }
        public Nullable<double> Disability_Services { get; set; }
        public Nullable<double> Mental_Health_Services { get; set; }
        public Nullable<double> Human_Health_Services_Sites { get; set; }
        public Nullable<double> Human_Health_Services_Types { get; set; }
        public Nullable<double> Dental_Sites { get; set; }
        public Nullable<double> General_Practice_Sites { get; set; }
        public Nullable<double> Pharmacy_Sites { get; set; }
        public Nullable<double> Allied_Health_Sites { get; set; }
        public Nullable<double> Complementary_Health_Sites { get; set; }
        public Nullable<double> Child_Care_Sites { get; set; }
        public Nullable<double> Residential_Aged_Care_Facilities { get; set; }
        public Nullable<double> Licensed_Aged_Care_Places { get; set; }
        public Nullable<double> Primary_Schools { get; set; }
        public Nullable<double> Secondary_School { get; set; }
        public Nullable<double> P12_schools { get; set; }
        public Nullable<double> Other_Schools { get; set; }
        public string Nearest_Health_Service { get; set; }
        public Nullable<double> Distance_to_Nearest_Health_Service { get; set; }
        public string Residential { get; set; }
        public string Business { get; set; }
        public string Industrial { get; set; }
        public string Rural { get; set; }
        public string Other { get; set; }
        public Nullable<double> Number_Of_Households { get; set; }
        public Nullable<double> Persons_Per_Household { get; set; }
        public string Population_In_nonprivate_Dwellings { get; set; }
        public string Public_Rental_Dwellings { get; set; }
        public string Aboriginal_Or_Torres_Strait_Islander { get; set; }
        public string Not_Completed_Year_12 { get; set; }
        public string Unemployed_Persons { get; set; }
        public string Household_Income_Less_Than_650 { get; set; }
        public string Individual_Income_Less_Than_400 { get; set; }
        public string Household_Without_Motor_Vehicle { get; set; }
        public string Household_With_Internet { get; set; }
        public string One_Parent_Headed_Families { get; set; }
        public string Persons_aged_75_Above_Living_Alone { get; set; }
        public string Need_Assistance_With_Core_Activities { get; set; }
        public string Born_Overseas { get; set; }
        public string Non_Engisdh_Speaker_At_Home { get; set; }
        public string Poor_English_Proficiency { get; set; }
        public string Main_Cultural_group_1_Name { get; set; }
        public string Main_cultural_group_1_Percentage { get; set; }
        public string Main_cultural_group_2_Name { get; set; }
        public string Main_cultural_group_2_Percentage { get; set; }
        public string Main_cultural_group_3_Name { get; set; }
        public string Main_cultural_group_3_Percentage { get; set; }
    }
}
